INSERT INTO products (product_id, name, description, price, category, stock, on_sale, hit_count) VALUES
(1, 'iphone', 'Latest model smartphone with high-end specs', 263.69, 'Electronics', 18, False, 87),
(2, 'Evo Laptop', 'Lightweight laptop with long battery life', 49.65, 'Electronics', 14, False, 83),
(3, 'SuperSmartwatch', 'Smartwatch with fitness tracking features', 18.47, 'Electronics', 95, False, 85),
(4, 'Aura Bluetooth Speaker', 'Portable speaker with excellent sound quality', 289.82, 'Electronics', 94, True, 84),
(5, 'Bango Wireless Earbuds', 'Noise-cancelling wireless earbuds', 434.22, 'Electronics', 28, False, 84),
(6, 'Mystery a  Novel', 'A thrilling mystery novel with unexpected twists', 337.94, 'Books', 13, False, 83),
(7, 'Science Fiction of the Futre', 'A futuristic science fiction book', 80.71, 'Books', 64, False, 84),
(8, 'Biography of Ed', 'Inspiring biography of a famous person', 62.00, 'Books', 99, True, 83),
(9, 'Help Book', 'Self-help book to improve your life', 273.94, 'Books', 56, False, 1),
(10, 'Anarchistic Cookbook', 'Recipe book with delicious recipes', 345.14, 'Books', 32, False, 84),
(11, 'White T-shirt', 'Comfortable cotton t-shirt', 478.65, 'Clothing', 40, False, 84),
(12, 'Billy Jeans', 'Stylish and durable jeans', 326.14, 'Clothing', 60, True, 83),
(13, 'Jaque Jacket', 'Warm and cozy jacket for winter', 230.25, 'Clothing', 59, False, 83),
(14, 'Jaammer Sneakers', 'Fashionable sneakers for everyday wear', 247.17, 'Clothing', 73, False, 83),
(15, 'Little Black Dress', 'Elegant dress for special occasions', 397.70, 'Clothing', 42, False, 84),
(16, 'Super Ultra Blender', 'High-speed blender for smoothies', 171.47, 'Home & Kitchen', 75, False, 83),
(17, 'Coffee Maker', 'Automatic coffee maker with timer', 263.26, 'Home & Kitchen', 49, True, 83),
(18, 'Zoomer Vacuum Cleaner', 'Powerful vacuum cleaner for all surfaces', 120.75, 'Home & Kitchen', 24, False, 83),
(19, 'Microwave Oven', 'Compact microwave oven with multiple settings', 122.81, 'Home & Kitchen', 4, False, 83),
(20, 'Air Fryer Plus', 'Air fryer for healthy cooking', 390.71, 'Home & Kitchen', 54, False, 83),
(21, 'Pullte Tennis Racket', 'Lightweight tennis racket with good grip', 402.65, 'Sports & Outdoors', 63, False, 83),
(22, 'BlueMoon Yoga Mat', 'Non-slip yoga mat for all types of exercises', 357.62, 'Sports & Outdoors', 94, False, 84),
(23, 'HitchHiking Boots', 'Durable and comfortable hiking boots', 277.33, 'Sports & Outdoors', 67, False, 84),
(24, 'Flat Bicycle', 'Mountain bike with multiple gears', 278.80, 'Sports & Outdoors', 69, True, 84),
(25, 'Protestor Tent', 'Waterproof tent for camping', 346.79, 'Sports & Outdoors', 48, False, 98),
(26, 'Bald Shampoo', 'Nourishing shampoo for all hair types', 21.45, 'Beauty & Personal Care', 19, True, 83),
(27, 'Facial Cleanser', 'Gentle facial cleanser for daily use', 109.10, 'Beauty & Personal Care', 13, False, 83),
(28, 'Moisturizer', 'Hydrating moisturizer for smooth skin', 299.10, 'Beauty & Personal Care', 16, False, 82),
(29, 'Stinky Perfume', 'Long-lasting perfume with a pleasant fragrance', 15.90, 'Beauty & Personal Care', 43, False, 83),
(30, 'Lipstick Red', 'Matte finish lipstick in various shades', 11.01, 'Beauty & Personal Care', 5, True, 83),
(31, 'Smartphony', 'Latest model smartphone with high-end specs', 21.74, 'Electronics', 2, False, 85),
(32, 'Dell Laptop', 'Lightweight laptop with long battery life', 287.88, 'Electronics', 65, True, 83),
(33, 'FitSmartwatch', 'Smartwatch with fitness tracking features', 158.44, 'Electronics', 89, False, 85),
(34, 'Bingo Bluetooth Speaker', 'Portable speaker with excellent sound quality', 21.62, 'Electronics', 76, False, 84),
(35, 'Wireless Earbuds', 'Noise-cancelling wireless earbuds', 262.45, 'Electronics', 35, False, 84),
(36, 'Mystery Novella', 'A thrilling mystery novel with unexpected twists', 75.49, 'Books', 53, False, 83),
(37, 'Scienceless Fiction', 'A futuristic science fiction book', 83.13, 'Books', 87, True, 84),
(38, 'Self-helpless Book', 'Self-help book to improve your life', 425.46, 'Books', 96, True, 1),
(39, 'Canninabal Cookbook', 'Recipe book with delicious recipes', 161.08, 'Books', 81, False, 84),
(40, 'Bud Light T-shirt', 'Comfortable cotton t-shirt', 367.38, 'Clothing', 46, False, 84),
(41, 'DNAJeans', 'Stylish and durable jeans', 104.69, 'Clothing', 50, True, 83),
(42, 'Bonger Jacket', 'Warm and cozy jacket for winter', 446.56, 'Clothing', 73, False, 84),
(43, 'Sketchy Sneakers', 'Fashionable sneakers for everyday wear', 446.30, 'Clothing', 90, False, 84),
(44, 'BlueDress', 'Elegant dress for special occasions', 128.48, 'Clothing', 1, False, 84),
(45, 'Ultra Blender', 'High-speed blender for smoothies', 307.74, 'Home & Kitchen', 97, True, 83),
(46, 'BlackCoffee Maker', 'Automatic coffee maker with timer', 60.88, 'Home & Kitchen', 36, True, 84),
(47, 'Wacker Vacuum Cleaner', 'Powerful vacuum cleaner for all surfaces', 281.14, 'Home & Kitchen', 57, True, 83),
(48, 'Nuclear Microwave Oven', 'Compact microwave oven with multiple settings', 31.38, 'Home & Kitchen', 91, True, 83),
(49, 'ConAir Fryer', 'Air fryer for healthy cooking', 327.67, 'Home & Kitchen', 13, False, 83);
